# -*- coding: utf-8 -*-
"""CountNumberOfFaces.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aTpBsIMW-_-RmQLXXEV0mIRswvRF9A1-
"""

import cv2
import numpy as np
import dlib
from google.colab.patches import cv2_imshow

img = cv2.imread('img2.webp')

detector = dlib.get_frontal_face_detector()
img = cv2.flip(img,1)
imgGray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces = detector(imgGray)
i=0
for face in faces:
    x,y = face.left(),face.top()
    x1,y1 = face.right(),face.bottom()
    cv2.rectangle(img,(x,y),(x1,y1),(0,255,0),2)
    i = i+1
    cv2.putText(img,"face number "+str(i),(x-10,y-10),cv2.FONT_HERSHEY_SIMPLEX,0.7,(0,0,255),2)
    print(face,i)
cv2_imshow(img)
cv2.waitKey(0)
cv2.destroyAllWindows()